import React from "react";
import styled from "@emotion/styled";
/**
 * `<TaskDashboard>` ('Task Dashboard')
 * - [Open in Figma](https://figma.com/file/eXWhbKw2Iffo4JXjU5D8lJ?node-id=21:3)
 * - [Open in Grida](https://code.grida.co/files/eXWhbKw2Iffo4JXjU5D8lJ?node=21:3)
 *
 *
 * ---
 * @example
 * ```tsx
 * import React from "react";
 *
 * export default function () {
 *   return (
 *     <>
 *       👇 instanciate widget like below. 👇
 *       <TaskDashboard/>
 *     </>
 *   )
 * }
 * ```
 * ---
 * @params {any} props - this widget does not requires props. you can pass custom dynamic props to the widget as you want (on typescript, it will raise type check issues).
 * ---
 * @preview
 * ![](https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4bcda685-0ff6-448a-9ac2-9be7504cdf29)
 * ---
 * @remarks
 * @see {@link https://grida.co/docs} for more information.
 * ---
 * Code generated by grida.co | engine 0.0.1 (Apache-2.0) | Generated code under CC0 (public domain) *This code is free to use, modify, and redistribute. (aknowledgment is not required)*
 *
 *
 * ![Made with Grida](https://bridged-service-static.s3.us-west-1.amazonaws.com/branding/logo/32.png)
 * <!-- Info: Please do not remove this comment unless intended. removing this section will break grida integrations. -->
 * <!-- grida.meta.widget_declaration | engine : 0.0.1 | source : figma://eXWhbKw2Iffo4JXjU5D8lJ/21:3 -->
 */
export function CodeDuplication() {
  return (
    <RootWrapperTaskDashboard>
      <HiconOutlineActivity1
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9b96d602-a641-4fac-bf13-bde359c81a63"
        alt="icon"
      />
      <HiconOutlineGroup2
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/aba4e4f2-aeee-47bb-be03-bfb72ef084f6"
        alt="icon"
      />
      <HiconOutlineDocumentJustifyRight1
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d298b122-7092-4905-8e30-ca11c85c2016"
        alt="icon"
      />
      <HiconOutlineMessage18
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/1b9fbff5-7efa-4e86-9093-4d7c1d9fb813"
        alt="icon"
      />
      <IconlyBulkCategory
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/ac7ee296-d5c4-4747-b0bf-ed7cb7699762"
        alt="icon"
      />
      <Overview>Overview</Overview>
      <Analytics>Analytics</Analytics>
      <Analytics_0001>Analytics</Analytics_0001>
      <Analyze>analyze.</Analyze>
      <Analyze_0001>analyze.</Analyze_0001>
      <Cummunity>Cummunity</Cummunity>
      <Reports>Reports</Reports>
      <Support>Support</Support>
      <Settings>Settings</Settings>
      <Group1000002305>
        <Group1>
          <TrendingTopic1>
            <Vector xmlns="http://www.w3.org/2000/svg">
              <path
                fill="rgb(85, 52, 165)"
                d="M31.5851 14.2306C31.2721 13.9429 30.8328 13.8122 30.403 13.879C29.9724 13.9456 29.6005 14.2013 29.4008 14.5682C28.7138 15.8304 27.8412 16.9903 26.8145 18.0157C26.9169 17.275 26.9684 16.5299 26.9684 15.7827C26.9684 14.3491 26.7652 12.8739 26.3643 11.3974C25.0463 6.54784 21.5902 2.4466 16.8824 0.145382C16.4725 -0.0549006 15.9841 -0.0478685 15.5809 0.164134C15.1776 0.376224 14.9135 0.76507 14.8773 1.20001C14.5103 5.60711 12.11 9.61658 8.28825 12.203C8.23767 12.2375 8.18746 12.2724 8.13724 12.3071C8.03324 12.379 7.9352 12.4471 7.84358 12.5042C7.82926 12.5133 7.81504 12.5225 7.80108 12.5319C5.39747 14.1595 3.4142 16.329 2.06543 18.8066C0.694902 21.3268 0 24.0311 0 26.8444C0 28.2775 0.203146 29.7528 0.60384 31.2295C2.71838 39.0131 10.1249 44.4493 18.6152 44.4493C28.8791 44.4493 37.2293 36.5517 37.2293 26.8444C37.2293 22.0574 35.2249 17.5777 31.5851 14.2306L31.5851 14.2306Z"
              />
            </Vector>
            <Ellipse3 />
          </TrendingTopic1>
        </Group1>
      </Group1000002305>
      <Group1000002345>
        <Group1>
          <TrendingTopic1>
            <Vector xmlns="http://www.w3.org/2000/svg">
              <path
                fill="rgb(85, 52, 165)"
                d="M31.5851 14.2306C31.2721 13.9429 30.8328 13.8122 30.403 13.879C29.9724 13.9456 29.6005 14.2013 29.4008 14.5682C28.7138 15.8304 27.8412 16.9903 26.8145 18.0157C26.9169 17.275 26.9684 16.5299 26.9684 15.7827C26.9684 14.3491 26.7652 12.8739 26.3643 11.3974C25.0463 6.54784 21.5902 2.4466 16.8824 0.145382C16.4725 -0.0549006 15.9841 -0.0478685 15.5809 0.164134C15.1776 0.376224 14.9135 0.76507 14.8773 1.20001C14.5103 5.60711 12.11 9.61658 8.28825 12.203C8.23767 12.2375 8.18746 12.2724 8.13724 12.3071C8.03324 12.379 7.9352 12.4471 7.84358 12.5042C7.82926 12.5133 7.81504 12.5225 7.80108 12.5319C5.39747 14.1595 3.4142 16.329 2.06543 18.8066C0.694902 21.3268 0 24.0311 0 26.8444C0 28.2775 0.203146 29.7528 0.60384 31.2295C2.71838 39.0131 10.1249 44.4493 18.6152 44.4493C28.8791 44.4493 37.2293 36.5517 37.2293 26.8444C37.2293 22.0574 35.2249 17.5777 31.5851 14.2306L31.5851 14.2306Z"
              />
            </Vector>
            <Ellipse3 />
          </TrendingTopic1>
        </Group1>
      </Group1000002345>
      <Subtract
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/4bcda685-0ff6-448a-9ac2-9be7504cdf298"
        alt="image of Subtract"
      />
      <Rectangle5 />
      <Group1000002306>
        <Ellipse6 />
        <_2>2</_2>
      </Group1000002306>
      <Line1 />
      <Rectangle9 />
      <Rectangle10 />
      <Rectangle13 />
      <Rectangle23 />
      <Rectangle15 />
      <Rectangle14 />
      <Vector_0002
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9afe1d78-eb15-4743-9dc3-6e74c6032f4e"
        alt="icon"
      />
      <SearchHere>Search here...</SearchHere>
      <September>September</September>
      <Monday4ThSeptember>Monday, 4th September</Monday4ThSeptember>
      <IconlyLightOutlineCalendar
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d494e1b6-cfc1-47ee-a3c5-fda390a5e133"
        alt="icon"
      />
      <NaN_0001>+</NaN_0001>
      <AddTask>Add Task</AddTask>
      <Rectangle16 />
      <_3>3</_3>
      <_4>4</_4>
      <_5>5</_5>
      <_6>6</_6>
      <_7>7</_7>
      <_8>8</_8>
      <Mon>mon</Mon>
      <_0900>09:00</_0900>
      <_0900>10:00</_0900>
      <_0900>11:00</_0900>
      <_0900>12:00</_0900>
      <_0900>01:00</_0900>
      <Tue>tue</Tue>
      <Wed>wed</Wed>
      <Thu>thu</Thu>
      <Fri>fri</Fri>
      <Sat>sat</Sat>
      <Line3 />
      <Line4 />
      <Line5 />
      <Line6 />
      <Line7 />
      <Rectangle18 />
      <Rectangle21 />
      <Rectangle20 />
      <Rectangle22 />
      <Group1000002344>
        <UiMotion>UI Motion</UiMotion>
        <_1000Am1200Pm>10:00am - 12:00pm</_1000Am1200Pm>
      </Group1000002344>
      <Group1000002343>
        <_1200Pm0100Pm>12:00pm - 01:00pm</_1200Pm0100Pm>
        <UiDesign>UI Design</UiDesign>
      </Group1000002343>
      <Group1000002307>
        <Ellipse7 />
        <Ellipse8 />
        <Ellipse9 />
      </Group1000002307>
      <Group1000002308>
        <Ellipse7 />
        <Ellipse8 />
        <Ellipse9 />
      </Group1000002308>
      <Assignments>Assignments</Assignments>
      <_12>(12)</_12>
      <_25Completed>2/5 completed</_25Completed>
      <Vector_0003
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d298b122-7092-4905-8e30-ca11c85c20166"
        alt="icon"
      />
      <Rectangle30 />
      <Mon_0001>Mon</Mon_0001>
      <Tue_0001>Tue</Tue_0001>
      <Wed_0001>Wed</Wed_0001>
      <Thu_0001>Thu</Thu_0001>
      <Fri_0001>Fri</Fri_0001>
      <Sat_0001>Sat</Sat_0001>
      <Sun>Sun</Sun>
      <Frame2>
        <Group1000002348>
          <Group1000002309
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/d298b122-7092-4905-8e30-ca11c85c20167"
            alt="icon"
          />
          <Group1000002319>
            <ColourTheory>Colour Theory</ColourTheory>
            <_01Sep2022>01 Sep 2022</_01Sep2022>
          </Group1000002319>
          <_86100>86/100</_86100>
          <Grade>Grade</Grade>
        </Group1000002348>
        <Group1000002347>
          <Group1000002309
            src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/fb2057d0-451d-4f2a-8841-d5d3a2aa52d9"
            alt="icon"
          />
          <Group1000002315>
            <_90100>90/100</_90100>
            <Grade_0001>Grade</Grade_0001>
          </Group1000002315>
          <Group1000002320>
            <DesignSystem>Design system</DesignSystem>
            <_01Sep2022_0001>01 Sep 2022</_01Sep2022_0001>
          </Group1000002320>
        </Group1000002347>
        <Group1000002347>
          <Group1000002311>
            <CombinedShape xmlns="http://www.w3.org/2000/svg">
              <path
                fill="rgb(234, 234, 234)"
                d="M16.2589 0C20.103 0 22.6857 2.6158 22.6857 6.5076L22.6857 15.4924C22.6857 19.3842 20.103 22 16.2577 22L6.42573 22C2.58164 22 0 19.3842 0 15.4924L0 6.5076C0 2.6158 2.58164 0 6.42573 0L16.2589 0ZM16.2589 1.65L6.42573 1.65C3.55599 1.65 1.70143 3.5563 1.70143 6.5076L1.70143 15.4924C1.70143 18.4437 3.55599 20.35 6.42573 20.35L16.2577 20.35C19.1286 20.35 20.9843 18.4437 20.9843 15.4924L20.9843 6.5076C20.9843 3.5563 19.1286 1.65 16.2589 1.65Z"
              />
            </CombinedShape>
          </Group1000002311>
          <_0100_0001>0 /100</_0100_0001>
          <ToDo>To Do</ToDo>
          <Group1000002323>
            <Group1000002322>
              <Group1000002322>
                <UserPersona>User persona</UserPersona>
                <_03Sep2022>03 Sep 2022</_03Sep2022>
              </Group1000002322>
            </Group1000002322>
          </Group1000002323>
        </Group1000002347>
        <Group1000002345_0001>
          <Group1000002311>
            <CombinedShape xmlns="http://www.w3.org/2000/svg">
              <path
                fill="rgb(234, 234, 234)"
                d="M16.2019 0C20.0326 0 22.6063 2.6158 22.6063 6.5076L22.6063 15.4924C22.6063 19.3842 20.0326 22 16.2008 22L6.40323 22C2.5726 22 0 19.3842 0 15.4924L0 6.5076C0 2.6158 2.5726 0 6.40323 0L16.2019 0ZM16.2019 1.65L6.40323 1.65C3.54354 1.65 1.69547 3.5563 1.69547 6.5076L1.69547 15.4924C1.69547 18.4437 3.54354 20.35 6.40323 20.35L16.2008 20.35C19.0616 20.35 20.9108 18.4437 20.9108 15.4924L20.9108 6.5076C20.9108 3.5563 19.0616 1.65 16.2019 1.65Z"
              />
            </CombinedShape>
          </Group1000002311>
          <Group1000002327>
            <ToDo_0001>To Do</ToDo_0001>
            <Group1000002317>
              <_0100_0002>0 /100</_0100_0002>
            </Group1000002317>
          </Group1000002327>
          <Group1000002324>
            <Prototyping>Prototyping</Prototyping>
            <_06Sep2022>06 Sep 2022</_06Sep2022>
          </Group1000002324>
        </Group1000002345_0001>
      </Frame2>
      <Frame1 />
      <Productivity>Productivity</Productivity>
      <Group1000002329
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/59c83e6d-7894-40f0-bb23-3cda202ef281"
        alt="icon"
      />
      <_6Hours24Min>6 hours 24 min</_6Hours24Min>
      <Line8 />
      <Line9 />
      <Line10 />
      <Line11 />
      <Line12 />
      <Line13 />
      <Line14 />
      <Rectangle48 />
      <Rectangle51 />
      <Rectangle53 />
      <Group1000002331>
        <Design>Design</Design>
        <Ellipse10 />
      </Group1000002331>
      <Group1000002332>
        <Animation>Animation</Animation>
        <Ellipse11 />
      </Group1000002332>
      <Group1000002330>
        <Research>Research</Research>
        <Ellipse12 />
      </Group1000002330>
      <Rectangle31 />
      <YourInterest>Your Interest</YourInterest>
      <Ellipse14
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/bbd73989-0d84-458b-bbcc-29587c3f9dc6"
        alt="image from ellipse"
      />
      <Ellipse14
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/9aa4d6d8-c22c-41c7-9d03-398e546d9f90"
        alt="image from ellipse"
      />
      <Ellipse14
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/271c4224-0d25-4874-9a87-11aa86267e7e"
        alt="image from ellipse"
      />
      <Ellipse17 />
      <_54H>54h</_54H>
      <Group1000002333>
        <Design_0001>Design</Design_0001>
        <Ellipse10_0001 />
      </Group1000002333>
      <Group1000002330_0001>
        <Research_0001>Research</Research_0001>
        <Ellipse12_0001 />
      </Group1000002330_0001>
      <Group1000002334>
        <Animation_0001>Animation</Animation_0001>
        <Ellipse11_0001 />
      </Group1000002334>
      <Rectangle24 />
      <Group1000002334>
        <HoursSpent>Hours Spent</HoursSpent>
        <_54Hours>54 hours</_54Hours>
      </Group1000002334>
      <Group1000002334>
        <TestResults>Test Results</TestResults>
        <_82>82%</_82>
      </Group1000002334>
      <Group1000002336>
        <Courses>Courses</Courses>
        <_02>02</_02>
      </Group1000002336>
      <Rectangle19 />
      <Rectangle26 />
      <Rectangle28 />
      <Line15 />
      <Line15 />
      <TimeCircle1
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/0394e35e-bae0-43fb-a7d9-b451d8e91929"
        alt="icon"
      />
      <Activity1
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/8ca2db77-728a-4728-9bec-3d4af8991388"
        alt="icon"
      />
      <Award3>
        <Subtract_0001 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(168, 92, 249)"
            d="M18 9.06977C18 14.0789 13.9706 18.1395 9 18.1395C4.02944 18.1395 0 14.0789 0 9.06977C0 4.06067 4.02944 0 9 0C13.9706 0 18 4.06067 18 9.06977Z"
          />
        </Subtract_0001>
      </Award3>
      <Rectangle54 />
      <Group1000002346_0001>
        <HoursSpent>Hours Spent</HoursSpent>
        <_54Hours>54 hours</_54Hours>
      </Group1000002346_0001>
      <Group1000002347_0001>
        <TestResults>Test Results</TestResults>
        <_82>82%</_82>
      </Group1000002347_0001>
      <Group1000002348_0001>
        <Courses>Courses</Courses>
        <_02>02</_02>
      </Group1000002348_0001>
      <Rectangle55 />
      <Rectangle56 />
      <Rectangle56 />
      <Line17 />
      <Line17 />
      <TimeCircle2
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/b7d42cdc-ee72-4039-859f-c946fc13fdad"
        alt="icon"
      />
      <Activity2
        src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/7ce9df9a-53c7-4499-8fd2-e32e3edad78b"
        alt="icon"
      />
      <Award4>
        <Subtract_0001 xmlns="http://www.w3.org/2000/svg">
          <path
            fill="rgb(168, 92, 249)"
            d="M18 9.06977C18 14.0789 13.9706 18.1395 9 18.1395C4.02944 18.1395 0 14.0789 0 9.06977C0 4.06067 4.02944 0 9 0C13.9706 0 18 4.06067 18 9.06977Z"
          />
        </Subtract_0001>
      </Award4>
      <Group1000002342>
        <Ellipse47 />
        <BellPin
          src="https://figma-alpha-api.s3.us-west-2.amazonaws.com/images/02081bd2-321d-4204-be2e-6bdfe591568b"
          alt="icon"
        />
      </Group1000002342>
    </RootWrapperTaskDashboard>
  );
}

const RootWrapperTaskDashboard = styled.div`
	min-height: 100vh;
	background-color: white;
	border-radius: 15px;
	position: relative;
`;

const HiconOutlineActivity1 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 32px;
	top: 202px;
	right: 1386px;
	bottom: 772px;
`;

const HiconOutlineGroup2 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 32px;
	top: 265px;
	right: 1386px;
	bottom: 709px;
`;

const HiconOutlineDocumentJustifyRight1 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 32px;
	top: 330px;
	right: 1386px;
	bottom: 644px;
`;

const HiconOutlineMessage18 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 32px;
	top: 844px;
	right: 1386px;
	bottom: 130px;
`;

const IconlyBulkCategory = styled.img`
	object-fit: cover;
	position: absolute;
	left: 32px;
	top: 137px;
	right: 1386px;
	bottom: 837px;
`;

const Overview = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 66px;
	top: 138px;
	right: 1300px;
	bottom: 838px;
`;

const Analytics = styled.span`
	color: rgb(85, 52, 165);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 66px;
	top: 203px;
	right: 1304px;
	bottom: 773px;
`;

const Analytics_0001 = styled.span`
	color: rgb(19, 15, 38);
	text-overflow: ellipsis;
	font-size: 32px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 600;
	text-align: left;
	position: absolute;
	left: 284px;
	top: 43px;
	right: 1013px;
	bottom: 913px;
`;

const Analyze = styled.span`
	color: rgb(19, 15, 38);
	text-overflow: ellipsis;
	font-size: 22px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 600;
	text-align: left;
	position: absolute;
	left: 91px;
	top: 51px;
	right: 1261px;
	bottom: 917px;
`;

const Analyze_0001 = styled.span`
	color: rgb(19, 15, 38);
	text-overflow: ellipsis;
	font-size: 22px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 600;
	text-align: left;
	position: absolute;
	left: 83px;
	top: 443px;
	right: 1269px;
	bottom: 525px;
`;

const Cummunity = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 66px;
	top: 266px;
	right: 1285px;
	bottom: 710px;
`;

const Reports = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 66px;
	top: 331px;
	right: 1312px;
	bottom: 645px;
`;

const Support = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 66px;
	top: 845px;
	right: 1310px;
	bottom: 131px;
`;

const Settings = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 66px;
	top: 908px;
	right: 1309px;
	bottom: 68px;
`;

const Group1000002305 = styled.div`
	width: 47px;
	height: 44px;
	position: absolute;
	left: 30px;
	top: 44px;
`;

const Group1 = styled.div`
	width: 47px;
	height: 44px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const TrendingTopic1 = styled.div`
	overflow: hidden;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Vector = styled.svg`
	width: 37px;
	height: 44px;
	position: absolute;
	left: 5px;
	top: 0px;
	right: 5px;
	bottom: 0px;
`;

const Ellipse3 = styled.div`
	background-color: rgb(248, 248, 248);
	border-radius: 11px / 11px;
	position: absolute;
	left: 17px;
	top: 22px;
	right: 19px;
	bottom: 12px;
`;

const Group1000002345 = styled.div`
	width: 47px;
	height: 44px;
	position: absolute;
	left: 20px;
	top: 434px;
`;

const Subtract = styled.img`
	object-fit: cover;
	position: absolute;
	left: 34px;
	top: 909px;
	right: 1388px;
	bottom: 69px;
`;

const Rectangle5 = styled.div`
	background-color: rgb(85, 52, 165);
	border-radius: 30px;
	position: absolute;
	left: 32px;
	top: 202px;
	right: 1386px;
	bottom: 772px;
`;

const Group1000002306 = styled.div`
	position: absolute;
	left: 32px;
	top: 202px;
	right: 1386px;
	bottom: 772px;
`;

const Ellipse6 = styled.div`
	width: 24px;
	height: 24px;
	background-color: rgb(168, 92, 249);
	border-radius: 24px / 24px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const _2 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: Poppins, sans-serif;
	font-weight: 600;
	text-align: left;
	position: absolute;
	left: 9px;
	top: 3px;
`;

const Line1 = styled.div`
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 32px;
	top: 202px;
	right: 1386px;
	bottom: 772px;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const Rectangle9 = styled.div`
	width: 360px;
	height: 1024px;
	background-color: rgb(241, 238, 246);
	border: solid 1px rgb(234, 234, 234);
	border-top-left-radius: 20px;
	border-bottom-right-radius: 20px;
	position: absolute;
	left: 1080px;
	top: 0px;
`;

const Rectangle10 = styled.div`
	width: 300px;
	height: 50px;
	background-color: white;
	border: solid 1px rgb(234, 234, 234);
	border-radius: 10px;
	position: absolute;
	left: 1110px;
	top: 44px;
`;

const Rectangle13 = styled.div`
	width: 300px;
	height: 450px;
	background-color: white;
	border: solid 1px rgb(234, 234, 234);
	border-radius: 10px;
	position: absolute;
	left: 1110px;
	top: 114px;
`;

const Rectangle23 = styled.div`
	width: 300px;
	height: 368px;
	background-color: white;
	border: solid 1px rgb(234, 234, 234);
	border-radius: 10px;
	position: absolute;
	left: 1110px;
	top: 580px;
`;

const Rectangle15 = styled.div`
	width: 290px;
	height: 127px;
	background-color: rgb(241, 238, 246);
	border-radius: 10px;
	position: absolute;
	left: 1115px;
	top: 119px;
`;

const Rectangle14 = styled.div`
	width: 100px;
	height: 30px;
	background-color: white;
	border-radius: 10px;
	position: absolute;
	left: 1290px;
	top: 131px;
`;

const Vector_0002 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 1131px;
	top: 59px;
	right: 289px;
	bottom: 917px;
`;

const SearchHere = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 1162px;
	top: 59px;
	right: 159px;
	bottom: 917px;
`;

const September = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 600;
	text-align: left;
	position: absolute;
	left: 1130px;
	top: 134px;
	right: 201px;
	bottom: 837px;
`;

const Monday4ThSeptember = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 801px;
	top: 55px;
	right: 465px;
	bottom: 923px;
`;

const IconlyLightOutlineCalendar = styled.img`
	width: 16px;
	height: 16px;
	object-fit: cover;
	position: absolute;
	left: 774px;
	top: 55px;
`;

const NaN_0001 = styled.span`
	color: rgb(85, 52, 165);
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 800;
	text-align: left;
	position: absolute;
	left: 1303px;
	top: 131px;
`;

const AddTask = styled.span`
	color: rgb(85, 52, 165);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 1320px;
	top: 139px;
	right: 56px;
	bottom: 842px;
`;

const Rectangle16 = styled.div`
	width: 30px;
	height: 50px;
	background-color: rgb(85, 52, 165);
	border-radius: 5px;
	position: absolute;
	left: 1175px;
	top: 180px;
`;

const _3 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 800;
	text-align: left;
	position: absolute;
	left: 1139px;
	top: 182px;
	right: 291px;
	bottom: 794px;
`;

const _4 = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 800;
	text-align: left;
	position: absolute;
	left: 1185px;
	top: 182px;
	right: 244px;
	bottom: 794px;
`;

const _5 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 800;
	text-align: left;
	position: absolute;
	left: 1232px;
	top: 182px;
	right: 198px;
	bottom: 794px;
`;

const _6 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 800;
	text-align: left;
	position: absolute;
	left: 1278px;
	top: 182px;
	right: 152px;
	bottom: 794px;
`;

const _7 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 800;
	text-align: left;
	position: absolute;
	left: 1324px;
	top: 182px;
	right: 106px;
	bottom: 794px;
`;

const _8 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 800;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 265px;
	right: 1386px;
	bottom: 709px;
`;

const Mon = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 265px;
	right: 1386px;
	bottom: 709px;
`;

const _0900 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 265px;
	right: 1386px;
	bottom: 709px;
`;

const Tue = styled.span`
	color: white;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 265px;
	right: 1386px;
	bottom: 709px;
`;

const Wed = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 265px;
	right: 1386px;
	bottom: 709px;
`;

const Thu = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 265px;
	right: 1386px;
	bottom: 709px;
`;

const Fri = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 1323px;
	top: 209px;
	right: 105px;
	bottom: 772px;
`;

const Sat = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 1366px;
	top: 209px;
	right: 56px;
	bottom: 772px;
`;

const Line3 = styled.div`
	width: 211px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 1175px;
	top: 286px;
`;

const Line4 = styled.div`
	width: 211px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 1175px;
	top: 346px;
`;

const Line5 = styled.div`
	width: 211px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 1175px;
	top: 406px;
`;

const Line6 = styled.div`
	width: 211px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 1175px;
	top: 466px;
`;

const Line7 = styled.div`
	width: 211px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 1175px;
	top: 526px;
`;

const Rectangle18 = styled.div`
	width: 200px;
	height: 66px;
	background-color: white;
	border: solid 1px rgb(234, 234, 234);
	border-radius: 10px;
	position: absolute;
	left: 1185px;
	top: 310px;
`;

const Rectangle21 = styled.div`
	width: 200px;
	height: 66px;
	background-color: white;
	border: solid 1px rgb(234, 234, 234);
	border-radius: 10px;
	position: absolute;
	left: 1185px;
	top: 431px;
`;

const Rectangle20 = styled.div`
	width: 8px;
	height: 66px;
	background-color: rgb(85, 52, 165);
	border-radius: 10px;
	position: absolute;
	left: 1185px;
	top: 310px;
`;

const Rectangle22 = styled.div`
	width: 8px;
	height: 66px;
	background-color: rgb(85, 52, 165);
	border-radius: 10px;
	position: absolute;
	left: 1185px;
	top: 431px;
`;

const Group1000002344 = styled.div`
	width: 115px;
	height: 41px;
	position: absolute;
	left: 1206px;
	top: 322px;
`;

const UiMotion = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 30px;
	bottom: 21px;
`;

const _1000Am1200Pm = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 26px;
	right: -12px;
	bottom: 0px;
`;

const Group1000002343 = styled.div`
	width: 116px;
	height: 41px;
	position: absolute;
	left: 1206px;
	top: 443px;
`;

const _1200Pm0100Pm = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 26px;
	right: -12px;
	bottom: 0px;
`;

const UiDesign = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 32px;
	bottom: 21px;
`;

const Group1000002307 = styled.div`
	width: 16px;
	height: 4px;
	position: absolute;
	left: 1356px;
	top: 327px;
`;

const Ellipse7 = styled.div`
	width: 4px;
	height: 4px;
	background-color: black;
	border-radius: 4px / 4px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const Ellipse8 = styled.div`
	width: 4px;
	height: 4px;
	background-color: black;
	border-radius: 4px / 4px;
	position: absolute;
	left: 6px;
	top: 0px;
`;

const Ellipse9 = styled.div`
	width: 4px;
	height: 4px;
	background-color: black;
	border-radius: 4px / 4px;
	position: absolute;
	left: 12px;
	top: 0px;
`;

const Group1000002308 = styled.div`
	width: 16px;
	height: 4px;
	position: absolute;
	left: 1356px;
	top: 448px;
`;

const Assignments = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 600;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 330px;
	right: 1386px;
	bottom: 644px;
`;

const _12 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 16px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 330px;
	right: 1386px;
	bottom: 644px;
`;

const _25Completed = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 330px;
	right: 1386px;
	bottom: 644px;
`;

const Vector_0003 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 32px;
	top: 330px;
	right: 1386px;
	bottom: 644px;
`;

const Rectangle30 = styled.div`
	width: 500px;
	height: 360px;
	background-color: white;
	border: solid 1px rgb(234, 234, 234);
	border-radius: 10px;
	position: absolute;
	left: 544px;
	top: 588px;
`;

const Mon_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 570px;
	top: 662px;
	right: 840px;
	bottom: 319px;
`;

const Tue_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 844px;
	right: 1386px;
	bottom: 130px;
`;

const Wed_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 844px;
	right: 1386px;
	bottom: 130px;
`;

const Thu_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 844px;
	right: 1386px;
	bottom: 130px;
`;

const Fri_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 844px;
	right: 1386px;
	bottom: 130px;
`;

const Sat_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 844px;
	right: 1386px;
	bottom: 130px;
`;

const Sun = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 32px;
	top: 844px;
	right: 1386px;
	bottom: 130px;
`;

const Frame2 = styled.div`
	display: flex;
	justify-content: flex-start;
	flex-direction: column;
	align-items: flex-start;
	gap: 30px;
	box-sizing: border-box;
	position: absolute;
	left: 1127px;
	top: 680px;
	width: 261px;
	height: 234px;
`;

const Group1000002348 = styled.div`
	width: 261px;
	height: 36px;
	position: relative;
`;

const Group1000002309 = styled.img`
	width: 22px;
	height: 22px;
	object-fit: cover;
	position: absolute;
	left: 0px;
	top: 7px;
`;

const Group1000002319 = styled.div`
	width: 94px;
	height: 36px;
	position: absolute;
	left: 32px;
	top: 0px;
`;

const ColourTheory = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 0px;
	right: -12px;
	bottom: 18px;
`;

const _01Sep2022 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 21px;
	right: 11px;
	bottom: 0px;
`;

const _86100 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 211px;
	top: 0px;
	right: 0px;
	bottom: 18px;
`;

const Grade = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 224px;
	top: 21px;
	right: 0px;
	bottom: 0px;
`;

const Group1000002347 = styled.div`
	height: 36px;
	position: relative;
	align-self: stretch;
	flex-shrink: 0;
`;

const Group1000002315 = styled.div`
	width: 51px;
	height: 36px;
	position: absolute;
	left: 210px;
	top: 0px;
`;

const _90100 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 18px;
`;

const Grade_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 14px;
	top: 21px;
	right: 0px;
	bottom: 0px;
`;

const Group1000002320 = styled.div`
	width: 98px;
	height: 36px;
	position: absolute;
	left: 32px;
	top: 0px;
`;

const DesignSystem = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 0px;
	right: -12px;
	bottom: 18px;
`;

const _01Sep2022_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 21px;
	right: 15px;
	bottom: 0px;
`;

const Group1000002311 = styled.div`
	width: 23px;
	height: 22px;
	position: absolute;
	left: 0px;
	top: 7px;
`;

const CombinedShape = styled.svg`
	width: 23px;
	height: 22px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const _0100_0001 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 214px;
	top: 0px;
	right: -6px;
	bottom: 18px;
`;

const ToDo = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 227px;
	top: 21px;
	right: -6px;
	bottom: 0px;
`;

const Group1000002323 = styled.div`
	width: 92px;
	height: 36px;
	position: absolute;
	left: 33px;
	top: 0px;
`;

const Group1000002322 = styled.div`
	width: 92px;
	height: 36px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const UserPersona = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 0px;
	right: -12px;
	bottom: 18px;
`;

const _03Sep2022 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 2px;
	top: 21px;
	right: 3px;
	bottom: 0px;
`;

const Group1000002345_0001 = styled.div`
	height: 36px;
	position: relative;
	align-self: stretch;
	flex-shrink: 0;
`;

const Group1000002327 = styled.div`
	width: 46px;
	height: 36px;
	position: absolute;
	left: 215px;
	top: 0px;
`;

const ToDo_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 12px;
	top: 21px;
	right: -6px;
	bottom: 0px;
`;

const Group1000002317 = styled.div`
	width: 46px;
	height: 18px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const _0100_0002 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 0px;
	right: -6px;
	bottom: 0px;
`;

const Group1000002324 = styled.div`
	width: 83px;
	height: 36px;
	position: absolute;
	left: 33px;
	top: 0px;
`;

const Prototyping = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 18px;
`;

const _06Sep2022 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 2px;
	top: 21px;
	right: -10px;
	bottom: 0px;
`;

const Frame1 = styled.div`
	width: 100px;
	height: 100px;
	overflow: hidden;
	position: absolute;
	left: 121px;
	top: 367px;
`;

const Productivity = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 600;
	text-align: left;
	position: absolute;
	left: 564px;
	top: 609px;
	right: 759px;
	bottom: 362px;
`;

const Group1000002329 = styled.img`
	width: 19px;
	height: 19px;
	object-fit: cover;
	position: absolute;
	left: 891px;
	top: 614px;
`;

const _6Hours24Min = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 922px;
	top: 613px;
	right: 411px;
	bottom: 365px;
`;

const Line8 = styled.div`
	width: 200px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 582px;
	top: 686px;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const Line9 = styled.div`
	width: 200px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 652px;
	top: 686px;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const Line10 = styled.div`
	width: 200px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 722px;
	top: 686px;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const Line11 = styled.div`
	width: 200px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 792px;
	top: 686px;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const Line12 = styled.div`
	width: 200px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 862px;
	top: 686px;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const Line13 = styled.div`
	width: 200px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 932px;
	top: 686px;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const Line14 = styled.div`
	width: 200px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 1002px;
	top: 686px;
	transform: rotate(-270deg);
	transform-origin: top left;
`;

const Rectangle48 = styled.div`
	width: 260px;
	height: 20px;
	background-color: rgb(168, 92, 249);
	border-radius: 5px;
	position: absolute;
	left: 564px;
	top: 701px;
`;

const Rectangle51 = styled.div`
	width: 251px;
	height: 20px;
	background-color: rgb(85, 52, 165);
	border-radius: 5px;
	position: absolute;
	left: 712px;
	top: 768px;
`;

const Rectangle53 = styled.div`
	width: 235px;
	height: 20px;
	background-color: rgb(75, 123, 229);
	border-radius: 5px;
	position: absolute;
	left: 627px;
	top: 836px;
`;

const Group1000002331 = styled.div`
	width: 59px;
	height: 15px;
	position: absolute;
	left: 649px;
	top: 914px;
`;

const Design = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 18px;
	top: 0px;
	right: -12px;
	bottom: 0px;
`;

const Ellipse10 = styled.div`
	width: 11px;
	height: 11px;
	background-color: rgb(168, 92, 249);
	border-radius: 11px / 11px;
	position: absolute;
	left: -0px;
	top: 2px;
`;

const Group1000002332 = styled.div`
	width: 77px;
	height: 15px;
	position: absolute;
	left: 742px;
	top: 914px;
`;

const Animation = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 18px;
	top: 0px;
	right: -12px;
	bottom: 0px;
`;

const Ellipse11 = styled.div`
	width: 11px;
	height: 11px;
	background-color: rgb(85, 52, 165);
	border-radius: 11px / 11px;
	position: absolute;
	left: 0px;
	top: 2px;
`;

const Group1000002330 = styled.div`
	width: 72px;
	height: 15px;
	position: absolute;
	left: 854px;
	top: 914px;
`;

const Research = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 18px;
	top: 0px;
	right: -12px;
	bottom: 0px;
`;

const Ellipse12 = styled.div`
	width: 11px;
	height: 11px;
	background-color: rgb(75, 123, 229);
	border-radius: 11px / 11px;
	position: absolute;
	left: -0px;
	top: 2px;
`;

const Rectangle31 = styled.div`
	width: 240px;
	height: 439px;
	background-color: white;
	border: solid 1px rgb(234, 234, 234);
	border-radius: 10px;
	position: absolute;
	left: 284px;
	top: 509px;
`;

const YourInterest = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 600;
	text-align: left;
	position: absolute;
	left: 304px;
	top: 531px;
	right: 1004px;
	bottom: 440px;
`;

const Ellipse14 = styled.img`
	object-fit: contain;
	position: absolute;
	left: 66px;
	top: 138px;
	right: 1300px;
	bottom: 838px;
`;

const Ellipse17 = styled.div`
	border-radius: 101px / 101px;
	position: absolute;
	left: 66px;
	top: 138px;
	right: 1300px;
	bottom: 838px;
`;

const _54H = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 700;
	text-align: left;
	position: absolute;
	left: 66px;
	top: 138px;
	right: 1300px;
	bottom: 838px;
`;

const Group1000002333 = styled.div`
	position: absolute;
	left: 66px;
	top: 138px;
	right: 1300px;
	bottom: 838px;
`;

const Design_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 24px;
	top: 0px;
	right: -12px;
	bottom: 0px;
`;

const Ellipse10_0001 = styled.div`
	width: 15px;
	height: 15px;
	background-color: rgb(168, 92, 249);
	border-radius: 15px / 15px;
	position: absolute;
	left: 0px;
	top: 2px;
`;

const Group1000002330_0001 = styled.div`
	position: absolute;
	left: 66px;
	top: 138px;
	right: 1300px;
	bottom: 838px;
`;

const Research_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 24px;
	top: 0px;
	right: -12px;
	bottom: 0px;
`;

const Ellipse12_0001 = styled.div`
	width: 15px;
	height: 15px;
	background-color: rgb(75, 123, 229);
	border-radius: 15px / 15px;
	position: absolute;
	left: 0px;
	top: 2px;
`;

const Group1000002334 = styled.div`
	position: absolute;
	left: 801px;
	top: 55px;
	right: 465px;
	bottom: 923px;
`;

const Animation_0001 = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 14px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	position: absolute;
	left: 24px;
	top: 0px;
	right: -12px;
	bottom: 0px;
`;

const Ellipse11_0001 = styled.div`
	width: 15px;
	height: 15px;
	background-color: rgb(85, 52, 165);
	border-radius: 15px / 15px;
	position: absolute;
	left: 0px;
	top: 2px;
`;

const Rectangle24 = styled.div`
	background-color: white;
	border: solid 1px rgb(234, 234, 234);
	border-radius: 10px;
	position: absolute;
	left: 801px;
	top: 55px;
	right: 465px;
	bottom: 923px;
`;

const HoursSpent = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	min-height: 23px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: -6px;
	bottom: 30px;
`;

const _54Hours = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 600;
	text-align: left;
	min-height: 32px;
	position: absolute;
	left: 0px;
	top: 21px;
	right: -12px;
	bottom: 0px;
`;

const TestResults = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	min-height: 23px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: -12px;
	bottom: 30px;
`;

const _82 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 600;
	text-align: left;
	min-height: 32px;
	position: absolute;
	left: 0px;
	top: 21px;
	right: 33px;
	bottom: 0px;
`;

const Group1000002336 = styled.div`
	position: absolute;
	left: 66px;
	top: 203px;
	right: 1304px;
	bottom: 773px;
`;

const Courses = styled.span`
	color: rgb(117, 117, 117);
	text-overflow: ellipsis;
	font-size: 12px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 500;
	text-align: left;
	min-height: 23px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: -12px;
	bottom: 30px;
`;

const _02 = styled.span`
	color: black;
	text-overflow: ellipsis;
	font-size: 20px;
	font-family: "Plus Jakarta Sans", sans-serif;
	font-weight: 600;
	text-align: left;
	min-height: 32px;
	position: absolute;
	left: 0px;
	top: 21px;
	right: 110px;
	bottom: 0px;
`;

const Rectangle19 = styled.div`
	background-color: rgb(241, 238, 246);
	border-radius: 10px;
	position: absolute;
	left: 66px;
	top: 203px;
	right: 1304px;
	bottom: 773px;
`;

const Rectangle26 = styled.div`
	background-color: rgb(241, 238, 246);
	border-radius: 10px;
	position: absolute;
	left: 284px;
	top: 43px;
	right: 1013px;
	bottom: 913px;
`;

const Rectangle28 = styled.div`
	background-color: rgb(241, 238, 246);
	border-radius: 10px;
	position: absolute;
	left: 66px;
	top: 266px;
	right: 1285px;
	bottom: 710px;
`;

const Line15 = styled.div`
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 66px;
	top: 266px;
	right: 1285px;
	bottom: 710px;
`;

const TimeCircle1 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 66px;
	top: 266px;
	right: 1285px;
	bottom: 710px;
`;

const Activity1 = styled.img`
	object-fit: cover;
	position: absolute;
	left: 66px;
	top: 331px;
	right: 1312px;
	bottom: 645px;
`;

const Award3 = styled.div`
	position: absolute;
	left: 66px;
	top: 331px;
	right: 1312px;
	bottom: 645px;
`;

const Subtract_0001 = styled.svg`
	width: 18px;
	height: 26px;
	position: absolute;
	left: 0px;
	top: 0px;
	right: 0px;
	bottom: 0px;
`;

const Rectangle54 = styled.div`
	width: 243px;
	height: 358px;
	background-color: white;
	border: solid 1px rgb(234, 234, 234);
	border-radius: 10px;
	position: absolute;
	left: 662px;
	top: 126px;
`;

const Group1000002346_0001 = styled.div`
	width: 90px;
	height: 53px;
	position: absolute;
	left: 745px;
	top: 166px;
`;

const Group1000002347_0001 = styled.div`
	width: 80px;
	height: 54px;
	position: absolute;
	left: 750px;
	top: 392px;
`;

const Group1000002348_0001 = styled.div`
	width: 138px;
	height: 54px;
	position: absolute;
	left: 749px;
	top: 278px;
`;

const Rectangle55 = styled.div`
	width: 50px;
	height: 50px;
	background-color: rgb(241, 238, 246);
	border-radius: 10px;
	position: absolute;
	left: 682px;
	top: 164px;
`;

const Rectangle56 = styled.div`
	width: 50px;
	height: 50px;
	background-color: rgb(241, 238, 246);
	border-radius: 10px;
	position: absolute;
	left: 20px;
	top: 434px;
`;

const Line17 = styled.div`
	width: 178px;
	height: 0px;
	border-top: solid 1px rgb(234, 234, 234);
	position: absolute;
	left: 20px;
	top: 434px;
`;

const TimeCircle2 = styled.img`
	width: 20px;
	height: 20px;
	object-fit: cover;
	position: absolute;
	left: 20px;
	top: 434px;
`;

const Activity2 = styled.img`
	width: 20px;
	height: 20px;
	object-fit: cover;
	position: absolute;
	left: 20px;
	top: 434px;
`;

const Award4 = styled.div`
	width: 18px;
	height: 26px;
	position: absolute;
	left: 20px;
	top: 434px;
`;

const Group1000002342 = styled.div`
	width: 43px;
	height: 43px;
	position: absolute;
	left: 993px;
	top: 44px;
`;

const Ellipse47 = styled.div`
	width: 43px;
	height: 43px;
	background-color: rgb(241, 238, 246);
	border-radius: 43px / 43px;
	position: absolute;
	left: 0px;
	top: 0px;
`;

const BellPin = styled.img`
	width: 24px;
	height: 24px;
	object-fit: cover;
	position: absolute;
	left: 10px;
	top: 10px;
`;
