
import { BrowserRouter as Router, Routes, Route } from 'react-router-dom';
import { CodeDuplication } from './pages/codeDuplication';


function App() {

  return (
    <Router>
      <div className="App">

        <Routes>
          <Route exact path='/' element={< Home />}></Route>

          {/*<-----Grida Pages Generated------> */}

          {/* For Component Duplication */}
           <Route path = '/codeduplication' element = { <CodeDuplication/> } ></Route>
          {/* Using Grida for Individual Component generation - Can not use it for individual components */}

          {/* Page generated By CLI */}

          {/* Using Figma From Grida */}

          {/* Random Figma without Grida Guidelines */}

   </Routes>
    </div>
</Router >
  );
}

function Home() {
  return <h2>Home</h2>;
}

export default App;
